CREATE TABLE owner (
       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       name varchar(80) NOT NULL,
       surname varchar(80) NOT NULL,
       address varchar(80),
       tel int NOT NULL UNIQUE,
       UNIQUE(name, surname)
);
