DROP TABLE occurrence;
DROP TABLE disease;
DROP TABLE dog;
DROP TABLE owner;


CREATE TABLE owner (
       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       name varchar(80) NOT NULL,
       surname varchar(80) NOT NULL,
       address varchar(80),
       tel int NOT NULL
       UNIQUE (name, surname, tel)
);

CREATE TABLE dog (
       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
       owner_id int REFERENCES owner(id) NOT NULL,
       name varchar(80) NOT NULL,
       image_path varchar(256),
       date_of_birth date NOT NULL,
       sex char(1) NOT NULL,
       weight float(2) NOT NULL,
       breed varchar(80),
       CONSTRAINT optimus_prime CHECK (sex IN ('M', 'F'))
       UNIQUE(owner_id, name) --would a sane person name their animals the same name?
);

CREATE TABLE disease (
       name varchar(80) PRIMARY KEY,
       treatment varchar(256)
);

CREATE TABLE occurrence ( --fact of a disease occurance includes dog and its condition
       dog_id int REFERENCES dog(id) ON DELETE CASCADE, -- (jak usunie sie pies - to tez sie usunie. zablokjowanie usuniecia byloby ON DELETE RESTRICT)
       disease varchar(80) REFERENCES disease(name) ON DELETE CASCADE,
       entry_date date,
       CONSTRAINT name_disease_pk PRIMARY KEY (dog_id, disease) --cannot be sick two same diseases in a perfect world a dog gets better and never suffers from it again             
);
